### ISSUE TITLE
请教：go语言的apk如何用action编译

### ISSUE THREAD

**Issue by popococo-hanks-bocan** [Wsine/android_builder#1]
本人对apk编程不了解，搜索到这里的action方法。
把project改为https://github.com/p4gefau1t/trojan-go；
运行后提示golib无效。尝试了在build里改java为action里的go（乱改的，不懂），无效。
请大神有空时指导一下。多谢！

**Comment by Wsine** [comment]
这个仓库并不是一个 Android 项目。你的目标仓库里已有多个 action 样例可供参考如何编译构建，且目标仓库的 release 里已有预编译的产出了。
