### ISSUE TITLE
上传的问题

### ISSUE THREAD

**Issue by trytrytogo** [Wsine/android_builder#76]
工具很好用，但是在action里面的不太方面存放。
可否增加上传到**Releases**的操作呢？

另外，现在在编译的时候，有提示报错，但是不影响使用。
![image](https://user-images.githubusercontent.com/10056396/215378507-e886dcf7-4340-47bb-9123-d926d690b618.png)

**Comment by Wsine** [comment]
这个只是一个 Example Project，你可以根据自己的需要 fork 后更改。
