### ISSUE TITLE
出错了 下面提示 请问这么解决

### ISSUE THREAD

**Issue by lystv** [Wsine/android_builder#82]
* Get more help at https://help.gradle.org/

BUILD FAILED in 9s
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings
Error: Process completed with exit code 1.

**Comment by lystv** [comment]
可以到我fork的库看看 请指点一下谢谢
https://github.com/lystv/android_builder

**Comment by Wsine** [comment]
from https://github.com/lystv/android_builder/actions/runs/4239516250/jobs/7367645997 line 31

> Could not read script '/exo/core_settings.gradle' as it does not exist.

原仓库的编译问题，跟该自动化流程无关。
