### ISSUE TITLE
请帮忙

### ISSUE THREAD

**Issue by CojunM** [Wsine/android_builder#98]
Run if [ ! -f "gradlew" ]; then gradle wrapper; fi

Welcome to Gradle 8.2.1!

Here are the highlights of this release:
 - Kotlin DSL: new reference documentation, assignment syntax by default
 - Kotlin DSL is now the default with Gradle init
 - Improved suggestions to resolve errors in console output
 - Reduced sync memory consumption

For more details see https://docs.gradle.org/8.2.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Directory '/home/runner/work/android_builder/android_builder/project' does not contain a Gradle build.

A Gradle build should contain a 'settings.gradle' or 'settings.gradle.kts' file in its root directory. It may also contain a 'build.gradle' or 'build.gradle.kts' file.

To create a new Gradle build in this directory run 'gradle init'

For more information about the 'init' task, please refer to https://docs.gradle.org/8.2.1/userguide/build_init_plugin.html in the Gradle documentation.

For more details on creating a Gradle build, please refer to https://docs.gradle.org/8.2.1/userguide/tutorial_using_tasks.html in the Gradle documentation.

* Try:
> Run gradle init to create a new Gradle build in this directory.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org./

BUILD FAILED in 5s
Error: Process completed with exit code 1.

**Comment by Wsine** [comment]
Do not try to copy and paste and then wait for the solution.

To improve the quality of the open-source project, you'd better post a valuable problem. Spend some time on your issue description.

**Comment by CojunM** [comment]
https://github.com/CojunM/android_builder/actions/runs/5628390918
请看一下，是哪里的问题
